lab50:
  window:
    - editor
    - readme
    - terminal

submit50:
  files: &files
    - !exclude solutions.py "*.java"
    - !require hello.py

check50:
    files: *files
    hello world:
      - run: python3 hello.py # run python3 hello.py
        stdout: Hello, world! # expect Hello, world! in stdout
        exit: 0 # expect program to exit with exitcode 0

