lab50:
  window:
    - editor
    - readme
    - terminal

submit50:
  files: &files
    - !exclude solutions.py "*.java"
    - !require hello.py

check50:
  files: *files
  checks:
    hello world:
        stdout: Hello, world!
        exit: 0
