lab50:
  window:
    - editor
    - readme
    - terminal

submit50:
  files: &files
    - !exclude Greetings2.java
    - !require Greetings.java

check50:
  files: *files
  checks:
    hello world:
      - run: javac Greetings.java
      - run: java Greetings
        stdout: Hello, world!
        exit: 0
